import { Montserrat, Source_Code_Pro, Open_Sans } from "next/font/google";
import './global.css'

const montserrat = Montserrat({ subsets: ["latin"] });
const source_code_pro = Source_Code_Pro({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
